"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local .env (STRIPE keys, SECRET_KEY, etc.) — silently skipped if absent.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:  # python-dotenv not installed: rely on real environment vars
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The fallback below is a dev convenience ONLY — it is validated against DEBUG
# so it can never silently ship to production.
_INSECURE_DEV_KEY = 'django-insecure-l88&4z9wxa^19^suqzf3q+^_*7n7o0*rm+qr9@l8wqo6zdtzgc'
SECRET_KEY = os.environ.get('SECRET_KEY', _INSECURE_DEV_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False so a missing env var fails closed instead of leaking tracebacks.
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Fail fast if production is misconfigured with the public fallback key.
if not DEBUG and SECRET_KEY == _INSECURE_DEV_KEY:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        'SECRET_KEY environment variable must be set to a strong, unique value when DEBUG=False.'
    )

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    # Before django.contrib.admin on purpose: jazzmin ships replacements for
    # admin/base.html & friends, and app template dirs are searched in order, so
    # jazzmin's win only if it is listed first. Listing it after silently falls
    # back to Django's own unstyled theme.
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken', # 🌟 ADD THIS LINE
    'corsheaders',
    'products',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# PostgreSQL is the supported runtime database. SQLite is no longer used as a
# silent fallback (an unset/unreachable database should fail loudly, not quietly
# write to a local file). Configuration is resolved in this order so the same
# code runs locally, under docker-compose, and on Railway/Render/Heroku:
#
#   1. DATABASE_URL                    single URL — PaaS providers inject this
#   2. POSTGRES_* / PG* discrete vars  docker-compose, manual setups
#   3. local-development defaults      mirror docker-compose.yml
#
# Escape hatch: export DB_ENGINE=sqlite for throwaway local runs / the SQLite→
# PostgreSQL data dump. Never set it in production.

def _postgres_from_url(url):
    """Parse postgresql://user:pass@host:port/db into a Django DATABASES dict."""
    from urllib.parse import urlparse

    parsed = urlparse(url)
    if parsed.scheme not in ('postgres', 'postgresql'):
        raise ValueError(f'DATABASE_URL must use the postgresql:// scheme, got {parsed.scheme!r}')
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': parsed.path.lstrip('/') or 'maims_db',
        'USER': parsed.username or 'maims_user',
        'PASSWORD': parsed.password or '',
        'HOST': parsed.hostname or '127.0.0.1',
        'PORT': str(parsed.port or 5432),
    }


def _postgres_from_env():
    """Build a PostgreSQL config from discrete environment variables."""
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB') or os.environ.get('PGDATABASE') or 'maims_db',
        'USER': os.environ.get('POSTGRES_USER') or os.environ.get('PGUSER') or 'maims_user',
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD') or os.environ.get('PGPASSWORD') or 'maims_password',
        'HOST': os.environ.get('POSTGRES_HOST') or os.environ.get('PGHOST') or '127.0.0.1',
        'PORT': str(os.environ.get('POSTGRES_PORT') or os.environ.get('PGPORT') or 5432),
    }


if os.environ.get('DB_ENGINE', 'postgresql').lower() == 'sqlite':
    # Explicit opt-in only (local dev / data migration). Not a default.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    _database_url = os.environ.get('DATABASE_URL')
    _config = _postgres_from_url(_database_url) if _database_url else _postgres_from_env()
    # Reuse connections between requests when talking to PostgreSQL. Kept at 0
    # (no persistence) by default so short-lived/test processes stay predictable;
    # production should set DB_CONN_MAX_AGE (e.g. 600).
    _config['CONN_MAX_AGE'] = int(os.environ.get('DB_CONN_MAX_AGE', '0'))
    DATABASES = {'default': _config}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# --- django-jazzmin ------------------------------------------------------------
# Jazzmin replaces the admin's own theme (jQuery UI, buttons, tables, tabs, the
# responsive sidebar) with Bootstrap 4. The Maims dashboard, custom change forms
# and maims.css stay exactly as they are: jazzmin ships its own static files and
# all Maims templates extend "admin/base_site.html", which jazzmin re-skins.
# On narrow screens the sidebar collapses behind a "Maims Admin" toggle instead of
# the two-column squeeze the default theme suffers from.
# Set JAZZMIN_THEME='user-light' or 'cerulean' to change the palette.
JAZZMIN_THEME = os.environ.get('JAZZMIN_THEME', 'cerulean')
JAZZMIN_ADMIN_SITE_TITLE = 'Maims Admin'
JAZZMIN_WINDOW_TITLE = 'Maims Admin'

JAZZMIN_SETTINGS = {
    # Branding: drop the AdminLTE placeholder logo and the empty "Copyright 2026"
    # footer in favour of the shop's own name.
    'site_title': 'Maims Admin',
    'site_header': 'Maims Store Admin',
    'site_brand': 'Maims',
    'copyright': 'Maims — orders, stock and customers',
    'welcome_sign': 'Sign in to manage the shop',

    # Real icons instead of the generic grey dot on every model, so the sidebar
    # can be scanned by shape rather than by reading.
    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.user': 'fas fa-user',
        'auth.Group': 'fas fa-users',
        'products': 'fas fa-store',
        'products.order': 'fas fa-box-open',
        'products.product': 'fas fa-tag',
        'products.category': 'fas fa-sitemap',
        'products.collection': 'fas fa-layer-group',
        'products.heroslide': 'fas fa-images',
        'products.sitesettings': 'fas fa-cog',
    },

    # The sidebar and navbar stay put while you scroll a long product list, and
    # the "+ Add" button style follows the theme.
    'navbar_fixed': True,
    'sidebar_fixed': True,
    'footer_small_text': True,

    # Change forms are long on this site (product media, multi-currency prices).
    # Collapsible tabs show one section at a time instead of one long wall.
    'changeform_format': 'collapsible',

    # Opening a related object (a product from an order, a category from a
    # product) in a modal keeps the list you came from — no back-and-forth.
    'related_modal_active': True,

    # A light/dark toggle for staff working a dim packing table at night.
    'show_theme_chooser': True,
    'default_theme_mode': 'auto',

    # Open the whole catalogue from the navbar search box.
    'search_model': 'products.Product',

    # The two views staff open dozens of times a day, reachable from any page.
    # NB: jazzmin reads "name", not "title", and silently drops any link whose
    # listed permissions the signed-in staff member does not all hold.
    'topmenu_links': [
        {'name': 'Pack today', 'url': '/admin/products/order/?status__exact=new',
         'icon': 'fas fa-box-open', 'permissions': ['products.view_order']},
        {'name': 'Awaiting courier', 'url': '/admin/products/order/?status__exact=packed',
         'icon': 'fas fa-truck', 'permissions': ['products.view_order']},
        {'name': 'Sold out', 'url': '/admin/products/product/?stock_level=out',
         'icon': 'fas fa-triangle-exclamation', 'permissions': ['products.view_product']},
    ],

    # Plain "open the filtered list" shortcuts at the bottom of the Products group.
    'custom_links': {
        'products': [
            {'name': 'Update prices & stock (CSV)',
             'url': '/admin/products/product/import-csv/',
             'icon': 'fas fa-file-csv', 'permissions': ['products.change_product']},
        ],
    },
}
# Project-owned static files (admin/maims.css) live outside the app directories.
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS is allow-listed by default. Allow-all is only enabled when the operator
# explicitly opts in — it is NEVER auto-enabled just because DEBUG is on.
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False').lower() in ('true', '1', 'yes')
CORS_ALLOWED_ORIGINS = [o.strip() for o in os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173').split(',') if o.strip()]
# Auth uses the Authorization header (token), not cookies, so credentials aren't needed.
CORS_ALLOW_CREDENTIALS = False

# STRIPE CONFIGURATION
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')

# Real Live Email Settings Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Replace these with your actual details or environment variables:
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# The sender address customers will see
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@maims.app')

# The Admin email address that receives store notifications
ADMIN_RECEIVER_EMAIL = os.environ.get('ADMIN_RECEIVER_EMAIL', '')

# --- Transport & cookie hardening ---
SECURE_CONTENT_TYPE_NOSNIFF = True          # X-Content-Type-Options: nosniff
X_FRAME_OPTIONS = 'DENY'                    # clickjacking protection (admin included)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
# Secure cookies only once HTTPS is guaranteed (local dev is plain http).
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
# Trust the proxy's X-Forwarded-Proto header (Railway/Render/Heroku terminate TLS).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SECURE_SSL_REDIRECT = True              # force https
    SECURE_HSTS_SECONDS = 31536000          # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    # Fail closed: any view that forgets to declare permissions is private.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Scoped throttles attached to sensitive endpoints (login/register/checkout).
    'DEFAULT_THROTTLE_RATES': {
        'auth': os.environ.get('THROTTLE_AUTH', '10/min'),
        'checkout': os.environ.get('THROTTLE_CHECKOUT', '30/hour'),
    },
}