# Generated by Django 6.0.6 on 2026-06-29 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_orderitem_size_product_size_options_productmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stitching_selected',
            field=models.CharField(default='unstitched', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, help_text="e.g., Sana Safinaz, Maria.B (Since we aren't multi-vendor, this is just a label for filters)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_type',
            field=models.CharField(choices=[('lawn', 'Lawn'), ('silk', 'Silk'), ('organza', 'Organza'), ('velvet', 'Velvet'), ('cotton', 'Cotton'), ('chiffon', 'Chiffon'), ('other', 'Other Fabric')], default='lawn', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='stitching_type',
            field=models.CharField(choices=[('unstitched', 'Unstitched'), ('ready_to_wear', 'Ready to Wear'), ('both', 'Available in Both')], default='unstitched', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.collection'),
        ),
    ]
