# Generated by Django 6.0.6 on 2026-06-29 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_collection_category_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='material_type',
            field=models.CharField(blank=True, help_text="For jewelry/bags, e.g., 'Gold Plated', 'Genuine Leather'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, help_text='e.g., Sana Safinaz, Maria.B (Label used for frontend brand filtering)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric_type',
            field=models.CharField(blank=True, choices=[('lawn', 'Lawn'), ('silk', 'Silk'), ('organza', 'Organza'), ('velvet', 'Velvet'), ('cotton', 'Cotton'), ('chiffon', 'Chiffon'), ('other', 'Other Fabric')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_options',
            field=models.CharField(blank=True, help_text='Comma-separated options like S,M,L or One Size', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stitching_type',
            field=models.CharField(blank=True, choices=[('unstitched', 'Unstitched'), ('ready_to_wear', 'Ready to Wear'), ('both', 'Available in Both')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CurrencyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('SEK', 'Swedish Krona (kr)'), ('BDT', 'Bangladeshi Taka (৳)'), ('PKR', 'Pakistani Rupee (Rs)')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'currency')},
            },
        ),
    ]
