# Generated by Django 6.0.6 on 2026-10-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_price_product_material_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('SEK', 'Swedish Krona (kr)'), ('BDT', 'Bangladeshi Taka (৳)'), ('PKR', 'Pakistani Rupee (Rs)')], default='EUR', max_length=3),
        ),
    ]
