# Generated by Django 6.0.6 on 2026-10-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Elevate Your Everyday Style', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='Discover curated premium clothing collections tailored just for you.', null=True)),
                ('button_text', models.CharField(blank=True, default='Shop Latest Drop', max_length=100, null=True)),
                ('button_link', models.CharField(blank=True, default='#latest-products', help_text='Internal path like /category/women-clothing or #latest-products, or full https:// URL', max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/hero/')),
                ('external_image_url', models.URLField(blank=True, help_text='Optional: paste an https:// image URL instead of uploading', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('homepage_order', 'name'), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='homepage_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(default=True),
        ),
    ]
