# Generated by Django 6.0.6 on 2026-10-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_heroslide_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_page_url', models.URLField(blank=True, help_text='e.g. https://www.facebook.com/yourshop', null=True)),
                ('facebook_shop_url', models.URLField(blank=True, help_text='Optional: link to your Facebook Shop tab', null=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp Business number, digits only with country code, e.g. 351912345678', max_length=20, null=True)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('whatsapp_greeting', models.CharField(blank=True, default='Hello Maims! I want to order:', help_text='Prefill text before the cart details in the WhatsApp message', max_length=255, null=True)),
                ('cod_enabled', models.BooleanField(default=True, verbose_name='Cash on Delivery enabled')),
                ('stripe_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe (card)'), ('cod', 'Cash on Delivery'), ('whatsapp', 'WhatsApp order')], default='stripe', max_length=20),
        ),
    ]
