# Generated by Django 6.0.6 on 2026-10-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_sitesettings_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='e.g. https://www.instagram.com/yourshop', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='e.g. https://www.linkedin.com/company/yourshop', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='e.g. https://www.tiktok.com/@yourshop', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='e.g. https://x.com/yourshop', null=True, verbose_name='X (Twitter) URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='e.g. https://www.youtube.com/@yourshop', null=True),
        ),
    ]
